# Generated by Django 4.2 on 2025-05-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fullName',
            new_name='full_name',
        ),
    ]
