# Generated by Django 4.2 on 2025-05-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_services_active_days_services_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.ManyToManyField(to='MainApp.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.profile')),
            ],
        ),
    ]
