# Generated by Django 4.2 on 2025-05-20 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('house', models.CharField(max_length=200)),
                ('apartment', models.CharField(max_length=200)),
                ('comment_house', models.TextField()),
                ('date', models.DateTimeField()),
                ('pay_type', models.CharField(choices=[('card_online', 'Картой онлайн'), ('money', 'Наличными при визите'), ('card_offline', 'Картой при визите')], max_length=50)),
                ('comment', models.TextField()),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.basket')),
            ],
        ),
    ]
